data:
  path: data
  sep_token: "[SEP]"

train:
  awp: False
  gc: False
  checkpoint: medicalai/ClinicalBERT
  batch_size: 128
  lr: 8e-5
  wd: 0.01
  epochs: 15

create_csv: False
run_name: False
wandb: True

gc:
  type: "value"
  value: 1000
awp:
  start: 1
  adv_lr: 1e-4
  adv_eps: 1e-2